// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace TerpenesProject.Migrations
{
    [DbContext(typeof(TerpenesProjectDbContext))]
    [Migration("20240917072928_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.8");

            modelBuilder.Entity("TerpenesProject.Models.Condition", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Conditions");
                });

            modelBuilder.Entity("TerpenesProject.Models.Terpene", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Aroma")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Terpenes");
                });

            modelBuilder.Entity("TerpenesProject.Models.TerpeneCondition", b =>
                {
                    b.Property<Guid>("TerpeneId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ConditionId")
                        .HasColumnType("TEXT");

                    b.HasKey("TerpeneId", "ConditionId");

                    b.HasIndex("ConditionId");

                    b.ToTable("TerpenesConditions");
                });

            modelBuilder.Entity("TerpenesProject.Models.TerpeneCondition", b =>
                {
                    b.HasOne("TerpenesProject.Models.Condition", "Condition")
                        .WithMany("TerpeneConditions")
                        .HasForeignKey("ConditionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TerpenesProject.Models.Terpene", "Terpene")
                        .WithMany("TerpeneConditions")
                        .HasForeignKey("TerpeneId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Condition");

                    b.Navigation("Terpene");
                });

            modelBuilder.Entity("TerpenesProject.Models.Condition", b =>
                {
                    b.Navigation("TerpeneConditions");
                });

            modelBuilder.Entity("TerpenesProject.Models.Terpene", b =>
                {
                    b.Navigation("TerpeneConditions");
                });
#pragma warning restore 612, 618
        }
    }
}
